### ISSUE TITLE
QQ授权速度缓慢

### ISSUE THREAD

**Issue by yhhong** [Aoiujz/ThinkSDK#1]
在使用QQ，请求获取accesstoken，速度总是很慢，很影响体验。
再者QQ登陆比新浪微博还多了获取openid这一网络请求。速度实在慢

一半的几率是导致curl直接报超时错误的！

考虑是否应该改进curl针对请求qq授权的优化

**Comment by blu10ph** [comment]
这应该是个人开发环境的配置问题,请检查您的dns是否正常,我之前是dns出了问题,修改之后重启就好了~
